In [1]:
# paths in the format (action, next_state)
first_path = [(0, 1), (1, 1), (2, 1), (3, 0), (2, 2), (3, 2), (3, 2), (0, 4), (2, 5)]
second_path = [(0, 2), (0, 4), (3, 2), (3, 2), (3, 4), (2, 5)]
third_path = [(1, 0), (0, 2), (0, 4), (0, 4), (0, 4), (0, 4), (1, 2), (0, 4), (0, 4), (2, 5)]
third_path = [(1, 0), (0, 2), (2, 4), (0, 4), (1, 4), (3, 4), (1, 2), (0, 4), (2, 4), (2, 5)]
fourth_path = [(0, 2), (2, 3), (0, 5)]
fifth_path = [(3, 0), (0, 0), (0, 2), (0, 4), (3, 4), (1, 2), (0, 4), (0, 4), (0, 4), (1, 2), (0, 2), (3, 2), (2, 3), (0, 5)]

paths = [first_path, second_path, third_path, fourth_path, fifth_path]

### Q Learning

In [2]:
def Q_learning(Q, curr_state, R, action, next_state, gamma, alpha):
    # bellman equation
    Q_estimated = R[curr_state][next_state] +  gamma * max(Q[next_state])

    Q[curr_state, action] = Q[curr_state, action] + alpha * (Q_estimated - Q[curr_state, action])

    return Q

### Reward

In [3]:
import numpy as np

# R[state][next_state], i.e, reward gained going from 'state' to 'next_state'
R = np.full((6, 6), -1)

# hitting the wall (main diagonal)
R[0, 0] = -10
R[1, 1] = -10
R[2, 2] = -10
R[3, 3] = -10
R[4, 4] = -10

# going to the terminal state
R[:, 5] = 10

### Q matrix and parameters

In [4]:
# initial Q
Q = np.zeros((6, 4))

#parameters
alpha = 0.5
gamma = 1

### Update Q and Policy

In [5]:
# show Q matrix after each path
for i in range(len(paths)):
    # initial state
    curr_state = 0

    # updating Q
    for action, next_state in paths[i]:
        Q = Q_learning(Q, curr_state, R, action, next_state, gamma, alpha)
        curr_state = next_state

    # building policy
    actions = {0: "UP", 1: "DW", 2: "RG", 3: "LF"}
    policy = []
    for state in Q:
        # choosing the better action at each state
        policy.append(actions[np.argmax(state)])

    # output
    print_policy = f"{policy[4]} 10\n{policy[2]} {policy[3]}\n{policy[0]} {policy[1]}"
    print(f"- Trajetória {i + 1}\n{Q}\n\n{print_policy}\n")

- Trajetória 1
[[-0.5  0.  -0.5  0. ]
 [ 0.  -5.  -5.  -0.5]
 [-0.5  0.   0.  -7.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   5.   0. ]
 [ 0.   0.   0.   0. ]]

RG 10
DW UP
DW UP

- Trajetória 2
[[-0.75    0.     -0.5     0.    ]
 [ 0.     -5.     -5.     -0.5   ]
 [ 1.75    0.      0.     -1.9375]
 [ 0.      0.      0.      0.    ]
 [ 0.      0.      7.5     0.375 ]
 [ 0.      0.      0.      0.    ]]

RG 10
UP UP
DW UP

- Trajetória 3
[[ 0.     -5.     -0.5     0.    ]
 [ 0.     -5.     -5.     -0.5   ]
 [ 4.125   0.      3.25   -1.9375]
 [ 0.      0.      0.      0.    ]
 [-1.25    0.5     6.25   -1.0625]
 [ 0.      0.      0.      0.    ]]

RG 10
UP UP
UP UP

- Trajetória 4
[[ 1.5625 -5.     -0.5     0.    ]
 [ 0.     -5.     -5.     -0.5   ]
 [ 4.125   0.      1.125  -1.9375]
 [ 5.      0.      0.      0.    ]
 [-1.25    0.5     6.25   -1.0625]
 [ 0.      0.      0.      0.    ]]

RG 10
UP UP
UP UP

- Trajetória 5
[[-0.15625 -5.      -0.5     -4.21875]
 [ 0.      -5.      -5.      -0.5 